# -*- coding: utf-8 -*-
"""
/***************************************************************************
 alluvioni
                                 A QGIS plugin
 Il plugin serve a selezionare gli edifici coinvolti in caso di alluvione
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2021-08-06
        copyright            : (C) 2021 by FG
        email                : gianoli.federico@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'FG'
__date__ = '2021-08-06'
__copyright__ = '(C) 2021 by FG'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load alluvioni class from file alluvioni.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .alluvioni import alluvioniPlugin
    return alluvioniPlugin()
